### ISSUE TITLE
how are we using session variable in the JoinMeeting.js file?

### ISSUE THREAD

**Issue by abhimanusharma** [aws-samples/amazon-chime-sdk-pstn-integration#1]
I don't know if there is still moderator here or not but just wanted to know few things about this sample app.

1. How does `use('curl')` works?
2. what is **session** variable and how is it working in all over the JoinMeeting.js file with different-different functions, as there are no imports or require in the top of this file?
3. We do not provide any id to user to join the meeting, Is there a way for user to join the meeting using meeting url of our application?

**Comment by jkkorpi** [comment]
1. you must use the curl to make the post request to join the chime sdk meeting: ### curl.run("POST", `https://${api_host}/Prod/join?title=${meetingId}&name=${name}&region=${region}`, "", post_callback, "");
2. the session object is included with freeswitch: https://freeswitch.org/confluence/display/FREESWITCH/Session 
3. in this example, the meeting is started from another app where the id is generated. You could have additional participants via web or via PSTN phone. this is a sample project for a simple chimeSDK demo app: [deploying the serverless browser demo](https://github.com/aws/amazon-chime-sdk-js#deploying-the-serverless-browser-demo)
